from django.conf.urls import url
from kubehub.proxmox import proxmox_hard_drive_cleaning
from rest_framework_simplejwt import views as jwt_views
from kubehub.views import (
    proxmox_cloud_provider_view,
    k8s_cluster_view,
    get_deploy_logs,
    restart_kubespray_deploy_view,
    tamplate_view,
    vm_group_view,
    get_kube_config,
    kubernetes_version_view,
    os_image_view,
    account_view,
    cloud_provider_view,
    vm_type_view
)


urlpatterns = [
    url(
        r"^cloud-provider/list/all$",
        cloud_provider_view.all_cloud_provider_list,
        name="all_cloud_provider_list"
    ),
    url(
        r"^list$",
        proxmox_cloud_provider_view.proxmox_cloud_provider_list,
        name="proxmox_cloud_provider_list"
    ),
    url(
        r"^add$",
        proxmox_cloud_provider_view.proxmox_cloud_provider_add,
        name="proxmox_cloud_provider_add"
    ),
    url(
        r"^cloud-provider/remove$",
        cloud_provider_view.cloud_provider_remove,
        name="cloud_provider_remove"
    ),
    url(
        r"^edit$",
        proxmox_cloud_provider_view.proxmox_cloud_provider_edit,
        name="proxmox_cloud_provider_edit"
    ),
    url(
        r"^cluster/add$",
        k8s_cluster_view.kubernetes_cluster_add,
        name="cluster_add"
    ),
    url(
        r"^cluster/remove$",
        k8s_cluster_view.kubernetes_cluster_remove,
        name="cluster_remove",
    ),
    url(
        r"^cluster/list$",
        k8s_cluster_view.kubernetes_cluster_list,
        name="cluster_list"
    ),
    url(
        r"^kubespray/deploy/get/log$",
        get_deploy_logs.get_deploy_logs,
        name="kubespray_deploy_get_log",
    ),
    url(
        r"^kubespray/deploy/restart$",
        restart_kubespray_deploy_view.restart_kubespray_deploy,
        name="kubespray_deploy_restart",
    ),
    url(
        r"^vm/group/list$",
        vm_group_view.vm_group_list,
        name="virtual_machines_group_list",
    ),
    url(
        r"^vm/group/from/template/list$",
        vm_group_view.vm_group_from_template_list,
        name="vm_group_from_template_list",
    ),
    url(
        r"^vm/group/from/image/list$",
        vm_group_view.vm_group_from_image_list,
        name="vm_group_from_image_list",
    ),
    url(
        r"^vm/group/status$",
        vm_group_view.get_vm_group_status,
        name="vm_group_status"
    ),
    url(
        r"^vm/group/add$",
        vm_group_view.vm_group_add,
        name="virtual_machines_group_add"
    ),
    url(
        r"^vm/group/remove$",
        vm_group_view.vm_group_remove,
        name="virtual_machines_group_remove",
    ),
    url(
        r"^template/list$",
        tamplate_view.list_template,
        name="proxmox_template_list"),
    url(
        r"^template/populate$",
        tamplate_view.populate_template_list,
        name="proxmox_template_populate",
    ),
    url(
        r"^proxmox/clean$",
        proxmox_hard_drive_cleaning.proxmox_hard_drive_cleaning,
        name="proxmox_hard_drive_cleaning",
    ),
    url(
        r"^cluster/get/config$",
        get_kube_config.get_kube_config,
        name="cluster_get_config",
    ),
    url(
        r"^kubernetes/version/list$",
        kubernetes_version_view.kubernetes_version_list,
        name="kubernetes_version_list"
    ),
    url(
        r"^kubernetes/version/add$",
        kubernetes_version_view.kubernetes_version_add,
        name="kubernetes_version_add"
    ),
    url(
        r"^kubernetes/version/remove$",
        kubernetes_version_view.kubernetes_version_remove,
        name="kubernetes_version_remove"
    ),
    url(
        r"^vm/os-image/list$",
        os_image_view.os_image_list,
        name="os_image_list"
    ),
    url(
        r"^vm/os-image/add$",
        os_image_view.os_image_add,
        name="os_image_add"
    ),
    url(
        r"^vm/os-image/remove$",
        os_image_view.os_image_remove,
        name="os_image_remove"
    ),
    url(
        r'^account/add$',
        account_view.account_add,
        name='account_add'
    ),
    url(
        r'^account/list$',
        account_view.account_list,
        name='account_list'
    ),
    url(
        r'^account/remove$',
        account_view.account_remove,
        name='account_remove'
    ),
    url(
        r'^account/edit$',
        account_view.account_edit,
        name='account_edit'
    ),
    url(
        r'^account/get_account_data$',
        account_view.get_account_data,
        name='get_account_data'
    ),
    url(
        r'^account/login$',
        jwt_views.TokenObtainPairView.as_view(),
        name='login'
    ),
    url(
        r'^account/refresh-token$',
        jwt_views.TokenRefreshView.as_view(),
        name='token_refresh'
    ),
    url(
        r"^vm-type/list$",
        vm_type_view.vm_type_list,
        name="vm_type_list"
    ),
    url(
        r"^vm-type/add$",
        vm_type_view.vm_type_add,
        name="vm_type_add"
    ),
    url(
        r"^vm-type/edit$",
        vm_type_view.vm_type_edit,
        name="vm_type_edit"
    ),
]
