# Generated by Django 3.0.3 on 2020-03-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_type', models.CharField(choices=[('Proxmox', 'Proxmox'), ('AWS', 'AWS'), ('GCP', 'GCP')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vmid', models.IntegerField()),
                ('diskread', models.IntegerField()),
                ('template', models.BooleanField()),
                ('status', models.CharField(max_length=255)),
                ('disk', models.IntegerField()),
                ('node', models.CharField(max_length=255)),
                ('cpu', models.IntegerField()),
                ('diskwrite', models.IntegerField()),
                ('maxcpu', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('netin', models.IntegerField()),
                ('maxdisk', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('maxmem', models.IntegerField()),
                ('netout', models.IntegerField()),
                ('uptime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VMGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vmid', models.IntegerField()),
                ('ip', models.CharField(max_length=255)),
                ('template_id', models.IntegerField()),
                ('cloud_provider_id', models.IntegerField()),
                ('vm_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='kubehub.VMGroup')),
            ],
        ),
        migrations.CreateModel(
            name='KubernetesCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('k8s_version', models.CharField(max_length=255)),
                ('vm_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kubehub.VMGroup')),
            ],
        ),
    ]
