# Generated by Django 3.0.2 on 2020-01-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_group_name', models.CharField(max_length=255)),
                ('vm_ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cloudprovider',
            name='cp_type',
            field=models.CharField(choices=[('PROX_MOX', 'PROX_MOX'), ('AWS', 'AWS'), ('GCP', 'GCP')], max_length=20),
        ),
    ]
