# Generated by Django 3.0.3 on 2020-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualBoxCloudProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_type', models.CharField(choices=[('Proxmox', 'Proxmox'), ('AWS', 'AWS'), ('GCP', 'GCP'), ('VirtualBox', 'VirtualBox')], max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('api_endpoint', models.CharField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255, unique=True)),
                ('debian_supported_versions', models.CharField(choices=[('ubuntu-16.04.6-desktop-amd64', 'ubuntu-16.04.6-desktop-amd64'), ('ubuntu-18.04.4-desktop-amd64', 'ubuntu-18.04.4-desktop-amd64')], max_length=255)),
                ('img_format', models.CharField(choices=['iso', 'iso'], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='proxmoxcloudprovider',
            name='api_endpoint',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='proxmoxcloudprovider',
            name='cp_type',
            field=models.CharField(choices=[('Proxmox', 'Proxmox'), ('AWS', 'AWS'), ('GCP', 'GCP'), ('VirtualBox', 'VirtualBox')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxmoxcloudprovider',
            name='password',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
