# Generated by Django 3.0.3 on 2020-05-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.CharField(choices=[('VirtualBox', 'VirtualBox'), ('Proxmox_image_based', 'Proxmox_image_based'), ('Proxmox_template_based', 'Proxmox_template_based')], max_length=255)),
                ('cores', models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)])),
                ('memory', models.IntegerField(choices=[(1, 1), (2, 2), (4, 4), (8, 8), (16, 16)])),
                ('boot_disk', models.IntegerField(choices=[(32, 32), (64, 64), (128, 128), (256, 256), (512, 512)], default=32)),
                ('proxmox_image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='kubehub.OsImage')),
                ('proxmox_template', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='kubehub.Template')),
                ('vbox_image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='kubehub.VirtualBoxImage')),
            ],
        ),
    ]
