# Generated by Django 3.0.3 on 2020-02-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmgroup',
            name='status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloudprovider',
            name='api_endpoint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cloudprovider',
            name='cp_type',
            field=models.CharField(choices=[('Proxmox', 'Proxmox'), ('AWS', 'AWS'), ('GCP', 'GCP')], max_length=255),
        ),
        migrations.AlterField(
            model_name='cloudprovider',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cloudprovider',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
