# Generated by Django 3.0.3 on 2020-05-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmtype',
            name='platform_type',
        ),
        migrations.RemoveField(
            model_name='vmtype',
            name='proxmox_image',
        ),
        migrations.RemoveField(
            model_name='vmtype',
            name='proxmox_template',
        ),
        migrations.RemoveField(
            model_name='vmtype',
            name='vbox_image',
        ),
    ]
