# Generated by Django 3.0.3 on 2020-03-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0002_auto_20200226_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubesprayDeploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('successful', 'successful'), ('failed', 'failed')], max_length=255)),
                ('log_file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='vmgroup',
            name='status',
            field=models.CharField(choices=[('creating', 'creating'), ('running', 'running'), ('removing', 'removing'), ('removed', 'removed'), ('error', 'error')], max_length=255),
        ),
    ]
