# Generated by Django 3.0.3 on 2020-04-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0002_auto_20200430_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualboxcloudprovider',
            name='img_format',
        ),
    ]
