# Generated by Django 3.0.2 on 2020-02-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0002_auto_20200128_1132'),
        ('kubehub', '0002_auto_20200128_1204'),
    ]

    operations = [
    ]
