# Generated by Django 3.0.3 on 2020-05-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0002_auto_20200514_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualBoxVm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vmid', models.IntegerField()),
                ('ip', models.CharField(max_length=255)),
                ('cores', models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)], default=1)),
                ('sockets', models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)], default=1)),
                ('memory', models.IntegerField(choices=[(1024, 1024), (2048, 2048), (4096, 4096), (8192, 8192), (16384, 16384)], default=1024)),
                ('boot_disk', models.IntegerField(choices=[(32, 32), (64, 64), (128, 128), (256, 256), (512, 512)], default=32)),
                ('disk_type', models.CharField(choices=[('scsi0', 'scsi0'), ('virtio0', 'virtio0'), ('ide0', 'ide0'), ('sata0', 'sata0')], default='scsi0', max_length=255)),
                ('vbox_os_image', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='kubehub.VirtualBoxImage')),
                ('vm_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vbox_vms', to='kubehub.VMGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
