# Generated by Django 3.0.3 on 2020-04-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0003_remove_virtualboxcloudprovider_img_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_type', models.CharField(choices=[('Proxmox', 'Proxmox'), ('AWS', 'AWS'), ('GCP', 'GCP'), ('VirtualBox', 'VirtualBox')], max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('api_endpoint', models.CharField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255, unique=True)),
                ('os_type', models.CharField(choices=[('Microsoft Windows', 'Microsoft Windows'), ('Linux', 'Linux'), ('BSD', 'BSD'), ('Solaris', 'Solaris'), ('Mac OS X', 'Mac OS X'), ('IBM OS/2', 'IBM OS/2')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='virtualboxcloudprovider',
            name='os_type',
            field=models.ManyToManyField(to='kubehub.OperatingSystemType'),
        ),
    ]
