# Generated by Django 3.0.3 on 2020-03-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0003_auto_20200305_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kubespraydeploy',
            name='log_file_path',
        ),
        migrations.AddField(
            model_name='kubespraydeploy',
            name='k8s_cluster',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='kubehub.KubernetesCluster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kubespraydeploy',
            name='vm_group',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='kubehub.VMGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kubespraydeploy',
            name='status',
            field=models.CharField(choices=[('deploying', 'deploying'), ('successful', 'successful'), ('failed', 'failed')], max_length=255),
        ),
    ]
