# Generated by Django 3.0.2 on 2020-02-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0003_merge_20200203_1024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VmGroups',
            new_name='VMGroup',
        ),
    ]
