# Generated by Django 3.0.3 on 2020-03-09 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0003_auto_20200309_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='template_id',
        ),
        migrations.AddField(
            model_name='vm',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='kubehub.Template'),
            preserve_default=False,
        ),
    ]
