# Generated by Django 3.0.3 on 2020-03-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0004_auto_20200306_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubespraydeploy',
            name='k8s_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kubespray_deployments', to='kubehub.KubernetesCluster'),
        ),
    ]
