# Generated by Django 3.0.2 on 2020-02-10 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0004_auto_20200205_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vmid', models.IntegerField(max_length=255)),
                ('diskread', models.IntegerField(max_length=255)),
                ('template', models.BooleanField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('disk', models.IntegerField(max_length=255)),
                ('node', models.CharField(max_length=255)),
                ('cpu', models.IntegerField(max_length=255)),
                ('diskwrite', models.IntegerField(max_length=255)),
                ('maxcpu', models.IntegerField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('netin', models.IntegerField(max_length=255)),
                ('maxdisk', models.IntegerField(max_length=255)),
                ('mem', models.IntegerField(max_length=255)),
                ('maxmem', models.IntegerField(max_length=255)),
                ('netout', models.IntegerField(max_length=255)),
                ('uptime', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vmgroup',
            name='cloud_provider_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmgroup',
            name='template_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmgroup',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmgroup',
            name='vmid',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
