# Generated by Django 3.0.3 on 2020-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0004_auto_20200518_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='vboxvmgroup',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vboxvmgroup',
            name='status',
            field=models.CharField(choices=[('creating', 'creating'), ('running', 'running'), ('removing', 'removing'), ('removed', 'removed'), ('error', 'error')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vboxvmgroup',
            name='user_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
