# Generated by Django 3.0.3 on 2020-05-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0005_auto_20200518_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualboxvm',
            name='vm_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vbox_vms', to='kubehub.VboxVmGroup'),
        ),
    ]
