# Generated by Django 3.0.2 on 2020-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0005_auto_20200210_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='cpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='disk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='diskread',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='diskwrite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='maxcpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='maxdisk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='maxmem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='mem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='netin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='netout',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='uptime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='vmid',
            field=models.IntegerField(),
        ),
    ]
