# Generated by Django 3.0.3 on 2020-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0005_auto_20200306_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubespraydeploy',
            name='status',
            field=models.CharField(choices=[('deploying', 'deploying'), ('ready_to_deploy', 'ready_to_deploy'), ('successful', 'successful'), ('failed', 'failed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='kubespraydeploy',
            name='vm_group',
            field=models.CharField(max_length=255),
        ),
    ]
