# Generated by Django 3.0.3 on 2020-03-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0006_auto_20200306_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubespraydeploy',
            name='vm_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kubehub.VMGroup'),
        ),
    ]
