# Generated by Django 3.0.2 on 2020-02-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0006_auto_20200210_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmgroup',
            old_name='vm_group_name',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='vmgroup',
            old_name='vm_ip',
            new_name='name',
        ),
    ]
