# Generated by Django 3.0.3 on 2020-03-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0007_auto_20200306_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubespraydeploy',
            name='vm_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kubespray_deployments', to='kubehub.VMGroup'),
        ),
    ]
