# Generated by Django 3.0.3 on 2020-03-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0008_auto_20200309_0938'),
        ('kubehub', '0004_auto_20200309_1945'),
    ]

    operations = [
    ]
