# Generated by Django 3.0.3 on 2020-03-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0009_merge_20200310_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubespraydeploy',
            name='status',
            field=models.CharField(choices=[('deploying', 'deploying'), ('successful', 'successful'), ('failed', 'failed')], max_length=255),
        ),
    ]
