# Generated by Django 3.0.3 on 2020-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0010_auto_20200310_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetescluster',
            name='status',
            field=models.CharField(choices=[('ready_to_deploy', 'ready_to_deploy'), ('deploying', 'deploying'), ('running', 'running'), ('removing', 'removing'), ('removed', 'removed'), ('error', 'error')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
