# Generated by Django 3.0.3 on 2020-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0011_kubernetescluster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetescluster',
            name='status',
            field=models.CharField(choices=[('deploying', 'deploying'), ('running', 'running'), ('removing', 'removing'), ('removed', 'removed'), ('error', 'error')], max_length=255),
        ),
    ]
