# Generated by Django 3.0.3 on 2020-03-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0012_auto_20200311_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='vmid',
            field=models.IntegerField(unique=True),
        ),
    ]
