# Generated by Django 3.0.3 on 2020-03-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0013_auto_20200318_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubernetesVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('v1.14.9', 'v1.14.9'), ('v1.15.3', 'v1.15.3'), ('v1.15.8', 'v1.15.8'), ('v1.15.11', 'v1.15.11'), ('v1.16.8', 'v1.16.8')], max_length=255)),
            ],
        ),
    ]
