# Generated by Django 3.0.3 on 2020-03-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0015_auto_20200327_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kubernetescluster',
            old_name='kubernetes_version',
            new_name='kubernetes_version_id',
        ),
    ]
