# Generated by Django 3.0.3 on 2020-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0016_auto_20200330_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='template',
        ),
        migrations.AddField(
            model_name='vm',
            name='boot_disk',
            field=models.IntegerField(choices=[(8192, 8), (16384, 16), (32768, 32), (65536, 64)], default=8192),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='cores',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='memory',
            field=models.IntegerField(choices=[(1024, 1), (2048, 2), (4096, 4), (8192, 8)], default=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='sockets',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)], default=1),
            preserve_default=False,
        ),
    ]
