# Generated by Django 3.0.3 on 2020-04-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0017_auto_20200414_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmFromImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vmid', models.IntegerField()),
                ('ip', models.CharField(max_length=255)),
                ('cores', models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)])),
                ('sockets', models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)])),
                ('memory', models.IntegerField(choices=[(1024, 1024), (2048, 2048), (4096, 4096), (8192, 8192)])),
                ('boot_disk', models.IntegerField(choices=[(16, 16), (32, 32), (64, 64), (128, 128)])),
                ('cloud_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='kubehub.CloudProvider')),
                ('vm_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='kubehub.VMGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='VM',
        ),
    ]
