# Generated by Django 3.0.3 on 2020-04-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0018_auto_20200415_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmFromTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vmid', models.IntegerField()),
                ('ip', models.CharField(max_length=255)),
                ('cloud_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='kubehub.CloudProvider')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='kubehub.Template')),
                ('vm_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='kubehub.VMGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
