# Generated by Django 3.0.3 on 2020-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0020_auto_20200416_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vmid', models.IntegerField(unique=True)),
                ('os_type', models.CharField(choices=[('wxp', 'wxp'), ('w2k', 'w2k'), ('w2k3', 'w2k3'), ('w2k8', 'w2k8'), ('wvista', 'wvista'), ('win7', 'win7'), ('win8', 'win8'), ('win10', 'win10'), ('l24', 'l24'), ('l26', 'l26'), ('solaris', 'solaris')], default='l26', max_length=255)),
                ('bios', models.CharField(choices=[('seabios', 'seabios'), ('ovmf', 'ovmf')], default='seabios', max_length=255)),
                ('scsi_controller_model', models.CharField(choices=[('lsi', 'lsi'), ('lsi53c810', 'lsi53c810'), ('virtio-scsi-pci ', 'virtio-scsi-pci'), ('virtio-scsi-single', 'virtio-scsi-single'), ('megasas', 'megasas'), ('pvscsi', 'pvscsi')], default='virtio-scsi-pci', max_length=255)),
                ('storage', models.CharField(max_length=255)),
            ],
        ),
    ]
