# Generated by Django 3.0.3 on 2020-04-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0021_osimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osimage',
            name='scsi_controller_model',
            field=models.CharField(choices=[('lsi', 'lsi'), ('lsi53c810', 'lsi53c810'), ('virtio-scsi-pci', 'virtio-scsi-pci'), ('virtio-scsi-single', 'virtio-scsi-single'), ('megasas', 'megasas'), ('pvscsi', 'pvscsi')], default='virtio-scsi-pci', max_length=255),
        ),
    ]
