# Generated by Django 3.0.3 on 2020-04-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0022_auto_20200416_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='osimage',
            name='agent',
            field=models.CharField(choices=[('enabled=0', 'enabled=0'), ('enabled=1', 'enabled=1')], default='enabled=1', max_length=255),
        ),
    ]
