# Generated by Django 3.0.3 on 2020-04-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0023_osimage_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmfromimage',
            name='os_image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='kubehub.OsImage'),
            preserve_default=False,
        ),
    ]
