# Generated by Django 3.0.3 on 2020-04-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0024_vmfromimage_os_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmfromtemplate',
            name='boot_disk',
            field=models.IntegerField(choices=[(32, 32), (64, 64), (128, 128), (256, 256), (512, 512)], default=32),
        ),
        migrations.AddField(
            model_name='vmfromtemplate',
            name='cores',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)], default=1),
        ),
        migrations.AddField(
            model_name='vmfromtemplate',
            name='memory',
            field=models.IntegerField(choices=[(1024, 1024), (2048, 2048), (4096, 4096), (8192, 8192), (16384, 16384)], default=1024),
        ),
        migrations.AddField(
            model_name='vmfromtemplate',
            name='sockets',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)], default=1),
        ),
        migrations.AlterField(
            model_name='osimage',
            name='storage',
            field=models.CharField(default='local', max_length=255),
        ),
        migrations.AlterField(
            model_name='vmfromimage',
            name='boot_disk',
            field=models.IntegerField(choices=[(32, 32), (64, 64), (128, 128), (256, 256), (512, 512)], default=32),
        ),
        migrations.AlterField(
            model_name='vmfromimage',
            name='cores',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)], default=1),
        ),
        migrations.AlterField(
            model_name='vmfromimage',
            name='memory',
            field=models.IntegerField(choices=[(1024, 1024), (2048, 2048), (4096, 4096), (8192, 8192), (16384, 16384)], default=1024),
        ),
        migrations.AlterField(
            model_name='vmfromimage',
            name='os_image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='kubehub.OsImage'),
        ),
        migrations.AlterField(
            model_name='vmfromimage',
            name='sockets',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)], default=1),
        ),
        migrations.AlterField(
            model_name='vmfromtemplate',
            name='template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='kubehub.Template'),
        ),
    ]
