# Generated by Django 3.0.3 on 2020-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0025_auto_20200416_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmfromimage',
            name='disk_type',
            field=models.CharField(choices=[('scsi0', 'scsi0'), ('virtio0', 'virtio0'), ('ide0', 'ide0'), ('sata0', 'sata0')], default='scsi0', max_length=255),
        ),
        migrations.AddField(
            model_name='vmfromtemplate',
            name='disk_type',
            field=models.CharField(choices=[('scsi0', 'scsi0'), ('virtio0', 'virtio0'), ('ide0', 'ide0'), ('sata0', 'sata0')], default='scsi0', max_length=255),
        ),
    ]
