# Generated by Django 3.0.3 on 2020-04-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0026_auto_20200416_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmfromimage',
            name='cloud_provider',
        ),
        migrations.RemoveField(
            model_name='vmfromtemplate',
            name='cloud_provider',
        ),
        migrations.AddField(
            model_name='vmgroup',
            name='cloud_provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='kubehub.ProxmoxCloudProvider'),
        ),
        migrations.AlterField(
            model_name='vmfromimage',
            name='vm_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_vms', to='kubehub.VMGroup'),
        ),
        migrations.AlterField(
            model_name='vmfromtemplate',
            name='vm_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='template_vms', to='kubehub.VMGroup'),
        ),
    ]
