# Generated by Django 3.0.3 on 2020-04-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0027_auto_20200422_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxmoxcloudprovider',
            name='cp_type',
            field=models.CharField(choices=[('Proxmox', 'Proxmox'), ('AWS', 'AWS'), ('GCP', 'GCP')], max_length=255, null=True),
        ),
    ]
