# Generated by Django 3.0.3 on 2020-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubehub', '0028_auto_20200422_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxmoxcloudprovider',
            name='api_endpoint',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
